services:
  # Servicio web de Express
  - type: web
    name: auth-express-app
    runtime: node
    buildCommand: npm install && chmod +x scripts/render-setup.sh && ./scripts/render-setup.sh && npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /login
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auth-app-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PGHOST
        fromDatabase:
          name: auth-app-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: auth-app-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: auth-app-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: auth-app-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: auth-app-db
          property: port

# Base de datos PostgreSQL
databases:
  - name: auth-app-db
    plan: free
    ipAllowList: [] # acceso desde cualquier lugar