services:
  # Servicio web de Express
  - type: web
    name: auth-express-app
    runtime: node
    buildCommand: npm install && chmod +x scripts/render-setup.sh && ./scripts/render-setup.sh && npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /login
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_3O1bjMnLrwdE@ep-dawn-glade-a4oz3y8p-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SESSION_SECRET
        value: mi_secreto_seguro_para_sesiones_express_auth_demo
      - key: NODE_ENV
        value: production
      - key: SESSION_MAX_AGE
        value: 2592000000
      - key: PORT
        sync: false # Permitir que Render asigne su propio puerto
      - key: PUBLIC_URL
        value: https://auth-express-app.onrender.com